import Navbar from "@/components/navbar";

export const metadata = {
  title: "Record Store",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
        <div className='mt-[73px]'>
        {children}

        </div>
        
        </body>
    </html>
  );
}
